enum USER_RELATIONSHIPS {
    SINGLE = 'SINGLE',
    MARRIED = 'MARRIED',
    DIVORCED = 'DIVORCED',
    SEARCHING = 'SEARCHING',
}

enum USER_ACCESS_TYPES {
    USER = 'USER',
    ADMIN = 'ADMIN',
    SUPER_ADMIN = 'SUPER_ADMIN',
    BANNED = 'BANNED',
}

export { USER_RELATIONSHIPS, USER_ACCESS_TYPES };
